### ISSUE TITLE
Add User Agent

### ISSUE THREAD

**Issue by sprankhub** [elgentos/http-statuscode-checker#14]
Thanks for the nice tool!

One idea for improvement: Since some intense "crawling" can be done with this tool, it would be nice to add a user-agent to the requests, so that they can be easily identified on the server-side.

**Comment by peterjaap** [comment]
:heavy_check_mark:  https://github.com/elgentos/http-statuscode-checker/commit/0afdd97830f6cd55c73ba7ede32fbe84a65c3b90

**Comment by sprankhub** [comment]
Wow, that was fast. Thanks, @peterjaap!

**Comment by peterjaap** [comment]
We aim to please!
